USE [Alex_Demo1]
GO

/****** Object:  Table [dbo].[CSTHIST]    Script Date: 02/12/2013 14:22:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSTHIST](
	[year] [nvarchar](4) NULL,
	[account] [nvarchar](5) NULL,
	[postdate] [date] NULL,
	[jan_book] [numeric](10, 2) NULL,
	[jan_ship] [numeric](10, 2) NULL,
	[jan_sold] [numeric](10, 2) NULL,
	[jan_comm] [numeric](10, 2) NULL,
	[jan_retn] [numeric](10, 2) NULL,
	[jan_db] [numeric](10, 2) NULL,
	[jan_cr] [numeric](10, 2) NULL,
	[jan_pymt] [numeric](10, 2) NULL,
	[feb_book] [numeric](10, 2) NULL,
	[feb_ship] [numeric](10, 2) NULL,
	[feb_cost] [numeric](10, 2) NULL,
	[feb_sold] [numeric](10, 2) NULL,
	[feb_comm] [numeric](10, 2) NULL,
	[feb_retn] [numeric](10, 2) NULL,
	[feb_db] [numeric](10, 2) NULL,
	[feb_cr] [numeric](10, 2) NULL,
	[feb_pymt] [numeric](10, 2) NULL,
	[mar_book] [numeric](10, 2) NULL,
	[mar_ship] [numeric](10, 2) NULL,
	[mar_cost] [numeric](10, 2) NULL,
	[mar_sold] [numeric](10, 2) NULL,
	[mar_comm] [numeric](10, 2) NULL,
	[mar_retn] [numeric](10, 2) NULL,
	[mar_db] [numeric](10, 2) NULL,
	[mar_cr] [numeric](10, 2) NULL,
	[mar_pymt] [numeric](10, 2) NULL,
	[apr_book] [numeric](10, 2) NULL,
	[apr_ship] [numeric](10, 2) NULL,
	[apr_cost] [numeric](10, 2) NULL,
	[apr_sold] [numeric](10, 2) NULL,
	[apr_comm] [numeric](10, 2) NULL,
	[apr_retn] [numeric](10, 2) NULL,
	[apr_db] [numeric](10, 2) NULL,
	[apr_cr] [numeric](10, 2) NULL,
	[apr_pymt] [numeric](10, 2) NULL,
	[may_book] [numeric](10, 2) NULL,
	[may_shp] [numeric](10, 2) NULL,
	[may_cost] [numeric](10, 2) NULL,
	[may_sold] [numeric](10, 2) NULL,
	[may_comm] [numeric](10, 2) NULL,
	[may_retn] [numeric](10, 2) NULL,
	[may_db] [numeric](10, 2) NULL,
	[may_cr] [numeric](10, 2) NULL,
	[may_pymt] [numeric](10, 2) NULL,
	[jun_book] [numeric](10, 2) NULL,
	[jun_ship] [numeric](10, 2) NULL,
	[jun_cost] [numeric](10, 2) NULL,
	[jun_sold] [numeric](10, 2) NULL,
	[jun_comm] [numeric](10, 2) NULL,
	[jun_retn] [numeric](10, 2) NULL,
	[jun_db] [numeric](10, 2) NULL,
	[jun_cr] [numeric](10, 2) NULL,
	[jun_pymt] [numeric](10, 2) NULL,
	[jul_book] [numeric](10, 2) NULL,
	[jul_ship] [numeric](10, 2) NULL,
	[jul_cost] [numeric](10, 2) NULL,
	[jul_sold] [numeric](10, 2) NULL,
	[jul_comm] [numeric](10, 2) NULL,
	[jul_retn] [numeric](10, 2) NULL,
	[jul_db] [numeric](10, 2) NULL,
	[jul_cr] [numeric](10, 2) NULL,
	[jul_pymt] [numeric](10, 2) NULL,
	[aug_book] [numeric](10, 2) NULL,
	[aug_ship] [numeric](10, 2) NULL,
	[aug_cost] [numeric](10, 2) NULL,
	[aug_sold] [numeric](10, 2) NULL,
	[aug_comm] [numeric](10, 2) NULL,
	[aug_retn] [numeric](10, 2) NULL,
	[aug_db] [numeric](10, 2) NULL,
	[aug_cr] [numeric](10, 2) NULL,
	[aug_pymt] [numeric](10, 2) NULL,
	[sep_book] [numeric](10, 2) NULL,
	[sep_ship] [numeric](10, 2) NULL,
	[sep_cost] [numeric](10, 2) NULL,
	[sep_sold] [numeric](10, 2) NULL,
	[sep_comm] [numeric](10, 2) NULL,
	[sep_retn] [numeric](10, 2) NULL,
	[sep_db] [numeric](10, 2) NULL,
	[sep_cr] [numeric](10, 2) NULL,
	[sep_pymt] [numeric](10, 2) NULL,
	[oct_book] [numeric](10, 2) NULL,
	[oct_ship] [numeric](10, 2) NULL,
	[oct_cost] [numeric](10, 2) NULL,
	[oct_sold] [numeric](10, 2) NULL,
	[oct_comm] [numeric](10, 2) NULL,
	[oct_retn] [numeric](10, 2) NULL,
	[oct_db] [numeric](10, 2) NULL,
	[oct_cr] [numeric](10, 2) NULL,
	[oct_pymt] [numeric](10, 2) NULL,
	[nov_book] [numeric](10, 2) NULL,
	[nov_ship] [numeric](10, 2) NULL,
	[nov_cost] [numeric](10, 2) NULL,
	[nov_sold] [numeric](10, 2) NULL,
	[nov_comm] [numeric](10, 2) NULL,
	[nov_retn] [numeric](10, 2) NULL,
	[nov_db] [numeric](10, 2) NULL,
	[nov_cr] [numeric](10, 2) NULL,
	[nov_pymt] [numeric](10, 2) NULL,
	[dec_book] [numeric](10, 2) NULL,
	[dec_ship] [numeric](10, 2) NULL,
	[dec_cost] [numeric](10, 2) NULL,
	[dec_sold] [numeric](10, 2) NULL,
	[dec_comm] [numeric](10, 2) NULL,
	[dec_retn] [numeric](10, 2) NULL,
	[dec_db] [numeric](10, 2) NULL,
	[dec_cr] [numeric](10, 2) NULL,
	[ytd_book] [numeric](10, 2) NULL,
	[ytd_ship] [numeric](10, 2) NULL,
	[ytd_cost] [numeric](10, 2) NULL,
	[ytd_sold] [numeric](10, 2) NULL,
	[ytd_comm] [numeric](10, 2) NULL,
	[ytd_retn] [numeric](10, 2) NULL,
	[ytd_db] [numeric](10, 2) NULL,
	[ytd_cr] [numeric](10, 2) NULL,
	[ytd_pymt] [numeric](10, 2) NULL,
	[daystopay] [numeric](10, 0) NULL,
	[days] [numeric](10, 0) NULL,
	[recflag] [nvarchar](1) NULL
) ON [PRIMARY]

GO

