USE [Alex_Demo1]
GO

/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 02/12/2013 15:00:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CUSTOMER](
	[account] [nvarchar](5) NULL,
	[store] [nvarchar](8) NULL,
	[type] [nvarchar](1) NULL,
	[billaddr] [nvarchar](1) NULL,
	[shipaddr] [nvarchar](1) NULL,
	[name] [nvarchar](30) NULL,
	[status] [nvarchar](1) NULL,
	[priority] [nvarchar](1) NULL,
	[division] [nvarchar](12) NULL,
	[factor] [nvarchar](5) NULL,
	[factacct] [nvarchar](11) NULL,
	[duns] [nvarchar](11) NULL,
	[dunsrate] [nvarchar](4) NULL,
	[addr1] [nvarchar](30) NULL,
	[addr2] [nvarchar](30) NULL,
	[city] [nvarchar](15) NULL,
	[state] [nvarchar](3) NULL,
	[zip] [nvarchar](10) NULL,
	[country] [nvarchar](10) NULL,
	[cntrycd] [nvarchar](2) NULL,
	[phone] [nvarchar](16) NULL,
	[upszone] [nvarchar](1) NULL,
	[upsplus] [numeric](3, 0) NULL,
	[buyer] [nvarchar](20) NULL,
	[keeper] [nvarchar](20) NULL,
	[phoneap] [nvarchar](16) NULL,
	[fax] [nvarchar](16) NULL,
	[email] [nvarchar](30) NULL,
	[stmt] [nvarchar](1) NULL,
	[note] [nvarchar](30) NULL,
	[crlimit] [numeric](8, 0) NULL,
	[cravail] [numeric](12, 2) NULL,
	[whencrlim] [date] NULL,
	[crexp] [date] NULL,
	[overdue] [numeric](3, 0) NULL,
	[interest] [numeric](6, 2) NULL,
	[disccd] [nvarchar](2) NULL,
	[discpcnt] [numeric](7, 4) NULL,
	[disccd1] [nvarchar](2) NULL,
	[discpcnt1] [numeric](7, 4) NULL,
	[disscd2] [nvarchar](2) NULL,
	[discpcnt2] [numeric](7, 4) NULL,
	[disccd3] [nvarchar](2) NULL,
	[discpcnt3] [numeric](7, 4) NULL,
	[disccd4] [nvarchar](2) NULL,
	[discpcnt4] [numeric](7, 4) NULL,
	[disccd5] [nvarchar](2) NULL,
	[dispcnt5] [numeric](7, 4) NULL,
	[markup] [numeric](5, 2) NULL,
	[agedate] [date] NULL,
	[current] [numeric](10, 2) NULL,
	[age30] [numeric](10, 2) NULL,
	[age60] [numeric](10, 2) NULL,
	[age90] [numeric](10, 2) NULL,
	[age120] [numeric](10, 2) NULL,
	[totage] [numeric](10, 2) NULL,
	[bigage] [numeric](10, 2) NULL,
	[bigdate] [date] NULL,
	[gback] [numeric](10, 2) NULL,
	[netbal] [numeric](10, 2) NULL,
	[ytdbal] [numeric](10, 2) NULL,
	[tcurr] [numeric](10, 2) NULL,
	[tage30] [numeric](10, 2) NULL,
	[tage60] [numeric](10, 2) NULL,
	[tage90] [numeric](10, 2) NULL,
	[tage120] [numeric](10, 2) NULL,
	[mktregion] [nvarchar](2) NULL,
	[class] [nvarchar](2) NULL,
	[terms] [nvarchar](2) NULL,
	[shipvia] [nvarchar](2) NULL,
	[spcinst] [nvarchar](2) NULL,
	[usercode] [nvarchar](2) NULL,
	[insurcd] [nvarchar](1) NULL,
	[histseq] [numeric](6, 0) NULL,
	[invcode] [nvarchar](1) NULL,
	[lstord] [date] NULL,
	[bigord] [numeric](10, 2) NULL,
	[entered] [date] NULL,
	[softlock] [nvarchar](1) NULL,
	[cbno] [numeric](6, 0) NULL,
	[lang2] [nvarchar](1) NULL,
	[wwmemo] [nvarchar](8) NULL,
	[glink] [nvarchar](3) NULL,
	[permid] [nvarchar](8) NULL,
	[bounceno] [numeric](3, 0) NULL,
	[vendor] [nvarchar](10) NULL,
	[vat1] [nvarchar](1) NULL,
	[vat2] [nvarchar](1) NULL,
	[agedays] [numeric](5, 0) NULL,
	[wstatus] [nvarchar](4) NULL,
	[salesrep] [nvarchar](4) NULL,
	[salesrepa] [nvarchar](3) NULL,
	[salesrepb] [nvarchar](3) NULL,
	[salesrepc] [nvarchar](3) NULL,
	[salesrepd] [nvarchar](3) NULL,
	[salesrepe] [nvarchar](3) NULL,
	[salesrepf] [nvarchar](3) NULL,
	[salesrepg] [nvarchar](3) NULL,
	[salesreph] [nvarchar](3) NULL,
	[salesrepi] [nvarchar](3) NULL,
	[salesrepj] [nvarchar](3) NULL,
	[salesrepk] [nvarchar](3) NULL,
	[salesrepl] [nvarchar](3) NULL,
	[salesrepx] [nvarchar](3) NULL,
	[commpcnt] [numeric](5, 2) NULL,
	[commpcnta] [numeric](5, 2) NULL,
	[commpcntb] [numeric](5, 2) NULL,
	[commpcntc] [numeric](5, 2) NULL,
	[commpcntd] [numeric](5, 2) NULL,
	[commpcnte] [numeric](5, 2) NULL,
	[commpcntf] [numeric](5, 2) NULL,
	[commpcntg] [numeric](5, 2) NULL,
	[commpcnth] [numeric](5, 2) NULL,
	[commpcnti] [numeric](5, 2) NULL,
	[commpcntj] [numeric](5, 2) NULL,
	[commpcntk] [numeric](5, 2) NULL,
	[commpcntl] [numeric](5, 2) NULL,
	[commpcntx] [numeric](5, 2) NULL,
	[salesrep2] [nvarchar](3) NULL,
	[salesrep2a] [nvarchar](3) NULL,
	[salesrep2b] [nvarchar](3) NULL,
	[salesrep2c] [nvarchar](3) NULL,
	[salesrep2d] [nvarchar](3) NULL,
	[salesrep2e] [nvarchar](3) NULL,
	[salesrep2f] [nvarchar](3) NULL,
	[salesrep2g] [nvarchar](3) NULL,
	[salesrep2h] [nvarchar](3) NULL,
	[salesrep2i] [nvarchar](3) NULL,
	[salesrep2j] [nvarchar](3) NULL,
	[salesrep2k] [nvarchar](3) NULL,
	[salesrep2l] [nvarchar](3) NULL,
	[salesrep2x] [nvarchar](3) NULL,
	[commpcnt2] [numeric](5, 2) NULL,
	[commpcnt2a] [numeric](5, 2) NULL,
	[commpcnt2b] [numeric](5, 2) NULL,
	[commpcnt2c] [numeric](5, 2) NULL,
	[commpcnt2d] [numeric](5, 2) NULL,
	[commpcnt2e] [numeric](5, 2) NULL,
	[commpcnt2f] [numeric](5, 2) NULL,
	[commpcnt2g] [numeric](5, 2) NULL,
	[commpcnt2h] [numeric](5, 2) NULL,
	[commpcnt2i] [numeric](5, 2) NULL,
	[commpcnt2j] [numeric](5, 2) NULL,
	[commpcnt2k] [numeric](5, 2) NULL,
	[commpcnt2l] [numeric](5, 2) NULL,
	[commpcnt2x] [numeric](5, 2) NULL,
	[markupa] [numeric](6, 2) NULL,
	[markupb] [numeric](6, 2) NULL,
	[markupc] [numeric](6, 2) NULL,
	[markupd] [numeric](6, 2) NULL,
	[markupe] [numeric](6, 2) NULL,
	[markupf] [numeric](6, 2) NULL,
	[markupg] [numeric](6, 2) NULL,
	[markuph] [numeric](6, 2) NULL,
	[markupi] [numeric](6, 2) NULL,
	[markupj] [numeric](6, 2) NULL,
	[markupk] [numeric](6, 2) NULL,
	[markupl] [numeric](6, 2) NULL,
	[markupx] [numeric](6, 2) NULL,
	[budgeta] [numeric](10, 2) NULL,
	[budgetb] [numeric](10, 2) NULL,
	[budgetc] [numeric](10, 2) NULL,
	[budgetd] [numeric](10, 2) NULL,
	[budgete] [numeric](10, 2) NULL,
	[budgetf] [numeric](10, 2) NULL,
	[budgetg] [numeric](10, 2) NULL,
	[budgeth] [numeric](10, 2) NULL,
	[budgeti] [numeric](10, 2) NULL,
	[budgetj] [numeric](10, 2) NULL,
	[budgetk] [numeric](10, 2) NULL,
	[budgetl] [numeric](10, 2) NULL,
	[budgetx] [numeric](10, 2) NULL,
	[pccodea] [nvarchar](2) NULL,
	[pccodeb] [nvarchar](2) NULL,
	[pccodec] [nvarchar](2) NULL,
	[pccoded] [nvarchar](2) NULL,
	[pccodee] [nvarchar](2) NULL,
	[pccodef] [nvarchar](2) NULL,
	[pccodeg] [nvarchar](2) NULL,
	[pccodeh] [nvarchar](2) NULL,
	[pccodei] [nvarchar](2) NULL,
	[pccodej] [nvarchar](2) NULL,
	[pccodek] [nvarchar](2) NULL,
	[pccdoel] [nvarchar](2) NULL,
	[pccodex] [nvarchar](2) NULL,
	[no_inv] [numeric](2, 0) NULL,
	[biladrcode] [nvarchar](8) NULL,
	[shpadrcode] [nvarchar](8) NULL,
	[oldcustid] [nvarchar](6) NULL,
	[recflag] [nvarchar](1) NULL,
	[fedid] [nvarchar](12) NULL
) ON [PRIMARY]

GO

